apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-image-filter
  name: backend-image-filter
spec:
  selector:
    service: backend-image-filter
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080